-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mbw_usercredit (
  mbwuc_id INT UNSIGNED NOT NULL,
  mbwuc_data BLOB NOT NULL,
  PRIMARY KEY(mbwuc_id)
) /*$wgDBTableOptions*/;
